---
title: "Introduction to dplyr"
output: learnr::tutorial
runtime: shiny_prerendered
editor_options: 
  chunk_output_type: inline
---

```{r child='setup.Rmd'}
#specific libraries
```

```{r, context="data", include=FALSE}
#download and prep data
library(BiocManager)
library(scRNAseq)
set.seed(42)

happy <- readr::read_csv("https://raw.githubusercontent.com/matthewhirschey/tidybiology.org/main/data/happy.csv")

happy_full <- 
  readr::read_csv("https://raw.githubusercontent.com/matthewhirschey/tidybiology.org/main/data/world-happiness-report-2021.csv") %>% 
  janitor::clean_names() %>% 
  dplyr::rename(region = regional_indicator)

# happy_join_one <- 
#   happy %>% 
#   inner_join(happy_full, by = "country_name") %>% 
#   select(country_name, healthy_life_expectancy)
# 
# happy_join <- 
#   happy_full %>% 
#   filter(!(country_name %in% happy$country_name)) %>% 
#   slice_sample(n = 5) %>% 
#   select(country_name, healthy_life_expectancy) %>%
#   bind_rows(happy_join_one) %>% 
#   .[-10 ,]
```

```{r child='2-objects/2-a-getting_to_know_your_data-r-video.Rmd'}
```

```{r child='2-objects/2-a-getting_to_know_your_data-r-exercise.Rmd'}
```

```{r child='2-objects/2-a-getting_to_know_your_data-r-quiz.Rmd'}
```

```{r child='2-objects/2-a-selecting_variables-r-video.Rmd'}
```

```{r child='2-objects/2-a-selecting_variables-r-exercise.Rmd'}
```

```{r child='2-objects/2-a-filtering_observations-r-video.Rmd'}
```

```{r child='2-objects/2-a-filtering_observations-r-exercise.Rmd'}
```

```{r child='2-objects/2-a-arranging_your_data-r-video.Rmd'}
```

```{r child='2-objects/2-a-adding_new_columns-r-video.Rmd'}
```

```{r child='2-objects/2-a-saving_your_work-r-video.Rmd'}
#no scratchpad
```

```{r child='2-objects/2-a-resources_and_cheatsheets-r-video.Rmd'}
```

```{r child='2-objects/2-a-dplyr_final_exercise-r-exercise.Rmd'}
```

`r next_module("3-a-data_visualization_with_ggplot-r-module.Rmd")`
