---
title: " "
output: html_document
runtime: shiny_prerendered
---

```{r context="setup", include=FALSE}
#guide is here
# https://rmarkdown.rstudio.com/authoring_shiny_prerendered.html
# https://pkgs.rstudio.com/learnr/articles/publishing.html

#install libraries
library(shiny)
library(shinyjs)
library(shinyWidgets)
library(tidyverse)

knitr::opts_chunk$set(echo = FALSE)
```

```{r data, include=FALSE}
df <- tribble(
    ~Question, ~Answer, ~Difficulty,
    "Which function would you use to choose particular rows?", "filter()", "easy",
    "Which function would you use to choose particular columns?", "select()", "easy",
    "Which geom_*() function would you use to make a scatter plot?", "geom_point()", "easy",
    "How does arrange() order numeric values?", "From lowest to highest", "easy",
    "group_by() works especially well with which other dplyr function?", "summarise()/summarize()", "easy",
    "'%>%' is knows as the...", "pipe operator", "easy",
    "In a tidy dataset, what's another term for rows?", "Observations", "easy",
    "In a tidy dataset, what's another term for columns?", "Variables", "easy",
    "Which function can we use to assign a title to a plot?", "labs()", "easy",
    "What kind of join is a semi-join?", "Filtering Join", "hard",
    "What are the two main parameters of pivot_wider()?", "names_from and values_from", "hard",
    "What are the two main parameters of across()?", ".cols and .fns", "hard",
    "Which selection helper can handle regular expressions?", "matches()", "hard",
    "What is the regex for searching for a literal '.'", "\\\\.", "hard",
    "Which Dplyr function would you use to avoid writing nested if/else statements?", "case_when()", "hard"
)
```

```{r, context="render"}
# Create output for our router in main UI of Shiny app.
fluidPage(
    useShinyjs(),
    titlePanel("Tidybiology Quiz"),
    
    fluidRow(
        column(3,
               prettySwitch(inputId = "switch", label = textOutput("Difficulty"), status = "danger"),
               # textOutput("Difficulty")
        ),
        
        hr(),
        
        column(3,
               tags$head(
                   tags$style(HTML('#question{background-color:blue;
                                color:white}'))
               ),
               actionButton("question", "Next Question", width = '150px', icon = icon('refresh')),
               tags$head(
                   tags$style(HTML('#answer{background-color:blue;
                                    color:white}'))
               ),
               uiOutput("button2")
        ),
        
        column(9,
               tags$head(
                   tags$style(HTML('#Question{font-size: 25px;
                                              text-align: center}'))
               ),
               textOutput("Question"),
               tags$head(
                   tags$style(HTML('#Answer{font-size: 25px;
                                         text-align: center;
                                         color:teal}'))
               ),
               textOutput("Answer")
        )
    )
)
```


```{r, context="server"}
observeEvent(input$switch, {
        output$Difficulty <- renderText({
            if_else(input$switch, "hard", "easy")
        })
    })
    
    df1 <- NULL
    df2 <- NULL
    observeEvent(input$question, {
        output$Answer <- renderText({})
        
        if(input$switch){
            df <- df %>% 
                filter(Difficulty == "hard")
            
            df1 <<- df[sample(nrow(df), 1), ]
            df2 <<- df1
            question <- df1$Question
            difficulty <- df1$Difficulty 
        } else {
            df <- df %>% 
                filter(Difficulty == "easy")
            
            df1 <<- df[sample(nrow(df), 1), ]
            df2 <<- df1
            question <- df1$Question   
            difficulty <- df1$Difficulty 
        }
        
        output$Question <- renderText({question})
        
        output$button2 <- renderUI({
            actionButton("answer", label = "Show Answer", width = '150px', icon = icon('check'))
        })
        
    })
    
    observeEvent(input$answer, {
        output$Answer <- renderText({})
        answer <- df2$Answer
        
        output$Answer <- renderText({answer})
        shinyjs::hide("answer")
    })
```

