---
title: "Introduction to Rstudio"
output: 
  ioslides_presentation:
    widescreen: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(knitr)
library(here)
library(rlang)
knitr::opts_chunk$set(echo = FALSE, 
                      fig.align="center")
source(here::here("code", "bespoke.R")) #loads custom objects
```


```{r child='objects/intro_to_pipe.Rmd'}

```

```{r child='objects/intro_to_R_packages.Rmd'}

```

```{r child='objects/intro_to_r.Rmd'}

```

```{r child='objects/intro_to_rmarkdown.Rmd'}

```

```{r child='objects/intro_to_rstudio.Rmd'}

```

```{r child='objects/intro_to_tidyverse.Rmd'}

```

```{r child='objects/01_r_demo.Rmd'}

```

```{r child='objects/02_rmd_exercise.Rmd'}

```

```{r child='objects/03_rmd_practice.Rmd'}

```

```{r child='objects/getting_to_know_your_data.Rmd'}

```

```{r child='objects/help.Rmd'}

```

```{r child='objects/import.Rmd'}

```

```{r child='objects/saving.Rmd'}

```

```{r child='objects/acknolwedgements.Rmd'}

```
