---
title: "stringr activity"
output: learnr::tutorial
runtime: shiny_prerendered
---
```{r, include = FALSE}
#load libraries
library(learnr)
library(downloadthis)
```

## stringr activity  
  
Click the following button to download an R markdown file that contains stringr exercises

```{r, echo = FALSE}
#make temp file
temp_rmd <- tempfile(pattern = "4-stringr_activity_file_", 
                     fileext = ".Rmd")
#download file to temp file
download.file(url = "https://raw.githubusercontent.com/matthewhirschey/tidybiology.org/main/code/4-objects/stringr_activity.Rmd", 
              destfile = temp_rmd)

#download button
downloadthis::download_file(
  path = temp_rmd,
  button_label = "Questions",
  button_type = "danger",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = TRUE
)
```

And here's another R markdown file with the answers  

```{r, echo = FALSE}
#make temp file
temp_rmd_answer <- tempfile(pattern = "4-stringr_activity_answers_file_", 
                     fileext = ".Rmd")
#download file to temp file
download.file(url = "https://raw.githubusercontent.com/matthewhirschey/tidybiology.org/main/code/4-objects/stringr_activity_answers.Rmd", 
              destfile = temp_rmd_answer)

#download button
downloadthis::download_file(
  path = temp_rmd_answer,
  button_label = "Answers",
  button_type = "warning",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = TRUE
)
```
